# Generated by Django 2.0 on 2017-12-31 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default="", blank=True, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
