# Generated by Django 2.0 on 2017-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171231_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place',
            field=models.CharField(blank=True, max_length=150, verbose_name='place'),
        ),
    ]
